In [1]:
import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

data = np.loadtxt(url, delimiter=',', usecols=(range(0, 4)))

print(data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [2]:
print(data.ndim)

2


In [3]:
first_col_mean = np.mean(data[:, 0])
first_col_median = np.median(data[:, 0])
first_col_standard = np.std(data[:, 0])

print(first_col_mean)
print(first_col_median)
print(first_col_standard)

5.843333333333334
5.8
0.8253012917851409


In [4]:
rand = np.random.default_rng()

randoms = rand.choice(data.size, size=20, replace=False)

data.flat[randoms] = np.nan

print(data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [nan 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 nan 0.2]
 [4.8 3.  1.4 0.1]
 [nan 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 nan nan 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  nan 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  nan 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [5]:
column = data[:, 0]
indexes = np.where(np.isnan(column))[0]

print(indexes)

[  3  13  59 133 144]


In [6]:
data[np.isnan(data)] = 0

print(data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [0.  3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 0.  0.2]
 [4.8 3.  1.4 0.1]
 [0.  3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 0.  0.  0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  0.  1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  0.  1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [7]:
data_filter = (data[:, 2] > 1.5) & (data[:, 0] < 5.0)
datas = data[data_filter]

print(datas)

[[4.8 3.4 1.9 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [0.  2.7 3.9 1.4]
 [4.9 2.5 4.5 1.7]
 [0.  2.8 5.1 1.5]
 [0.  3.3 5.7 2.5]]


In [8]:
n_columns = data.shape[1]

mid = n_columns // 2

left, right = np.split(data, [mid], axis=1)

print(left)
print(right)

[[5.1 3.5]
 [4.9 3. ]
 [4.7 3.2]
 [0.  3.1]
 [5.  3.6]
 [5.4 3.9]
 [4.6 3.4]
 [5.  3.4]
 [4.4 2.9]
 [4.9 3.1]
 [5.4 3.7]
 [4.8 3.4]
 [4.8 3. ]
 [0.  3. ]
 [5.8 4. ]
 [5.7 4.4]
 [5.4 3.9]
 [5.1 3.5]
 [5.7 3.8]
 [5.1 3.8]
 [5.4 3.4]
 [5.1 3.7]
 [4.6 3.6]
 [5.1 3.3]
 [4.8 3.4]
 [5.  3. ]
 [5.  3.4]
 [5.2 3.5]
 [5.2 3.4]
 [4.7 0. ]
 [4.8 3.1]
 [5.4 3.4]
 [5.2 4.1]
 [5.5 4.2]
 [4.9 3.1]
 [5.  0. ]
 [5.5 3.5]
 [4.9 3.1]
 [4.4 3. ]
 [5.1 3.4]
 [5.  3.5]
 [4.5 2.3]
 [4.4 3.2]
 [5.  3.5]
 [5.1 3.8]
 [4.8 3. ]
 [5.1 3.8]
 [4.6 3.2]
 [5.3 3.7]
 [5.  0. ]
 [7.  3.2]
 [6.4 3.2]
 [6.9 3.1]
 [5.5 2.3]
 [6.5 2.8]
 [5.7 2.8]
 [6.3 3.3]
 [4.9 2.4]
 [6.6 2.9]
 [0.  2.7]
 [5.  2. ]
 [5.9 3. ]
 [6.  2.2]
 [6.1 2.9]
 [5.6 2.9]
 [6.7 3.1]
 [5.6 3. ]
 [5.8 0. ]
 [6.2 2.2]
 [5.6 2.5]
 [5.9 3.2]
 [6.1 2.8]
 [6.3 2.5]
 [6.1 2.8]
 [6.4 2.9]
 [6.6 3. ]
 [6.8 2.8]
 [6.7 3. ]
 [6.  2.9]
 [5.7 2.6]
 [5.5 2.4]
 [5.5 2.4]
 [5.8 2.7]
 [6.  2.7]
 [5.4 3. ]
 [6.  3.4]
 [6.7 3.1]
 [6.3 2.3]
 [5.6 3. ]
 [5.5 2.5]
 [5.5 2.6]

In [9]:
idx_left = np.argsort(left[:, 0])
left_sorted = left[idx_left]

idx_right = np.argsort(-right[:, 0])
right_sorted = right[idx_right]

print(left_sorted)
print(right_sorted)

[[0.  3.1]
 [0.  3. ]
 [0.  2.7]
 [0.  2.8]
 [0.  3.3]
 [4.4 3.2]
 [4.4 3. ]
 [4.4 2.9]
 [4.5 2.3]
 [4.6 3.2]
 [4.6 3.6]
 [4.6 3.4]
 [4.7 0. ]
 [4.7 3.2]
 [4.8 3.1]
 [4.8 3.4]
 [4.8 3. ]
 [4.8 3. ]
 [4.8 3.4]
 [4.9 3.1]
 [4.9 3.1]
 [4.9 2.4]
 [4.9 3.1]
 [4.9 3. ]
 [4.9 2.5]
 [5.  3.4]
 [5.  3.4]
 [5.  2. ]
 [5.  0. ]
 [5.  3. ]
 [5.  0. ]
 [5.  3.5]
 [5.  2.3]
 [5.  3.5]
 [5.  3.6]
 [5.1 3.7]
 [5.1 3.5]
 [5.1 3.4]
 [5.1 3.8]
 [5.1 3.5]
 [5.1 3.8]
 [5.1 2.5]
 [5.1 3.3]
 [5.1 3.8]
 [5.2 3.4]
 [5.2 4.1]
 [5.2 3.5]
 [5.3 3.7]
 [5.4 3. ]
 [5.4 3.7]
 [5.4 3.4]
 [5.4 3.9]
 [5.4 3.9]
 [5.4 3.4]
 [5.5 4.2]
 [5.5 2.3]
 [5.5 2.4]
 [5.5 2.4]
 [5.5 2.5]
 [5.5 2.6]
 [5.5 3.5]
 [5.6 2.5]
 [5.6 3. ]
 [5.6 2.9]
 [5.6 2.8]
 [5.6 2.7]
 [5.6 3. ]
 [5.7 2.8]
 [5.7 4.4]
 [5.7 2.5]
 [5.7 2.9]
 [5.7 2.8]
 [5.7 3.8]
 [5.7 2.6]
 [5.7 3. ]
 [5.8 4. ]
 [5.8 2.7]
 [5.8 0. ]
 [5.8 2.8]
 [5.8 2.7]
 [5.8 2.6]
 [5.8 2.7]
 [5.9 3.2]
 [5.9 3. ]
 [5.9 3. ]
 [6.  2.9]
 [6.  3.4]
 [6.  2.7]
 [6.  2.2]
 [6.  2.2]
 [6.  3. ]

In [10]:
union_data = np.hstack((left_sorted, right_sorted))
print(union_data)

[[0.  3.1 6.9 2.3]
 [0.  3.  6.7 2.2]
 [0.  2.7 6.7 2. ]
 [0.  2.8 6.6 2.1]
 [0.  3.3 6.4 2. ]
 [4.4 3.2 6.3 1.8]
 [4.4 3.  6.1 1.9]
 [4.4 2.9 6.1 2.5]
 [4.5 2.3 6.1 2.3]
 [4.6 3.2 6.  1.8]
 [4.6 3.6 6.  2.5]
 [4.6 3.4 5.9 2.1]
 [4.7 0.  5.9 2.3]
 [4.7 3.2 5.8 2.2]
 [4.8 3.1 5.8 1.8]
 [4.8 3.4 5.8 1.6]
 [4.8 3.  5.7 2.1]
 [4.8 3.  5.7 2.3]
 [4.8 3.4 5.7 2.5]
 [4.9 3.1 5.6 1.4]
 [4.9 3.1 5.6 2.1]
 [4.9 2.4 5.6 2.2]
 [4.9 3.1 5.6 2.4]
 [4.9 3.  5.6 2.4]
 [4.9 2.5 5.6 1.8]
 [5.  3.4 5.5 1.8]
 [5.  3.4 5.5 1.8]
 [5.  2.  5.5 2.1]
 [5.  0.  5.4 2.1]
 [5.  3.  5.4 2.3]
 [5.  0.  5.3 2.3]
 [5.  3.5 5.3 1.9]
 [5.  2.3 5.2 2. ]
 [5.  3.5 5.2 2.3]
 [5.  3.6 5.1 1.9]
 [5.1 3.7 5.1 1.6]
 [5.1 3.5 5.1 2. ]
 [5.1 3.4 5.1 2.4]
 [5.1 3.8 5.1 1.9]
 [5.1 3.5 5.1 1.8]
 [5.1 3.8 5.1 1.5]
 [5.1 2.5 5.1 2.3]
 [5.1 3.3 5.  1.7]
 [5.1 3.8 5.  1.9]
 [5.2 3.4 5.  0. ]
 [5.2 4.1 5.  1.5]
 [5.2 3.5 4.9 1.8]
 [5.3 3.7 4.9 1.5]
 [5.4 3.  4.9 1.8]
 [5.4 3.7 4.9 2. ]
 [5.4 3.4 4.9 1.5]
 [5.4 3.9 4.8 0. ]
 [5.4 3.9 4.

In [11]:
uniques, counts = np.unique(union_data, return_counts=True)

for val, n in zip(uniques, counts):
    print(f"{val} - {n} times")

0.0 - 20 times
0.1 - 6 times
0.2 - 28 times
0.3 - 7 times
0.4 - 7 times
0.5 - 1 times
0.6 - 1 times
1.0 - 7 times
1.1 - 3 times
1.2 - 7 times
1.3 - 19 times
1.4 - 19 times
1.5 - 25 times
1.6 - 9 times
1.7 - 6 times
1.8 - 11 times
1.9 - 7 times
2.0 - 6 times
2.1 - 6 times
2.2 - 6 times
2.3 - 12 times
2.4 - 6 times
2.5 - 11 times
2.6 - 5 times
2.7 - 8 times
2.8 - 13 times
2.9 - 10 times
3.0 - 27 times
3.1 - 12 times
3.2 - 11 times
3.3 - 7 times
3.4 - 12 times
3.5 - 8 times
3.6 - 4 times
3.7 - 4 times
3.8 - 7 times
3.9 - 5 times
4.0 - 6 times
4.1 - 4 times
4.2 - 5 times
4.3 - 2 times
4.4 - 8 times
4.5 - 8 times
4.6 - 6 times
4.7 - 7 times
4.8 - 9 times
4.9 - 11 times
5.0 - 14 times
5.1 - 17 times
5.2 - 5 times
5.3 - 3 times
5.4 - 8 times
5.5 - 10 times
5.6 - 12 times
5.7 - 11 times
5.8 - 10 times
5.9 - 5 times
6.0 - 8 times
6.1 - 9 times
6.2 - 4 times
6.3 - 9 times
6.4 - 8 times
6.5 - 5 times
6.6 - 3 times
6.7 - 9 times
6.8 - 3 times
6.9 - 5 times
7.0 - 1 times
7.1 - 1 times
7.2 - 3 times

In [12]:
max_count_idx = np.argmax(counts)

num = uniques[max_count_idx]

print(num)

0.2


In [13]:
def func(col):
    mean = np.mean(col)

    result = np.where(col < mean, col * 2, col / 4)

    return result

In [14]:
print(data[:, 2])
data_func = func(data[:, 2])
print(data_func)

[1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 1.5 0.  1.4 1.1 1.2 1.5 1.3 1.4
 1.7 1.5 1.7 1.5 1.  1.7 1.9 1.6 1.6 1.5 1.4 0.  1.6 1.5 1.5 1.4 1.5 1.2
 1.3 1.5 1.3 1.5 1.3 1.3 1.3 1.6 1.9 1.4 1.6 1.4 1.5 1.4 4.7 4.5 4.9 4.
 4.6 4.5 4.7 3.3 4.6 3.9 3.5 4.2 4.  4.7 3.6 4.4 0.  4.1 4.5 3.9 4.8 4.
 4.9 4.7 4.3 4.4 4.8 5.  4.5 3.5 3.8 3.7 3.9 5.1 4.5 4.5 4.7 4.4 4.1 4.
 4.4 4.6 4.  3.3 4.2 4.2 4.2 4.3 3.  4.1 6.  5.1 5.9 5.6 5.8 6.6 4.5 6.3
 5.8 6.1 5.1 5.3 5.5 5.  5.1 5.3 5.5 6.7 6.9 5.  5.7 4.9 6.7 4.9 5.7 6.
 4.8 4.9 5.6 5.8 6.1 6.4 5.6 5.1 5.6 6.1 5.6 5.5 4.8 5.4 5.6 5.1 5.1 5.9
 5.7 5.2 5.  5.2 5.4 5.1]
[2.8   2.8   2.6   3.    2.8   3.4   2.8   3.    2.8   3.    3.    0.
 2.8   2.2   2.4   3.    2.6   2.8   3.4   3.    3.4   3.    2.    3.4
 3.8   3.2   3.2   3.    2.8   0.    3.2   3.    3.    2.8   3.    2.4
 2.6   3.    2.6   3.    2.6   2.6   2.6   3.2   3.8   2.8   3.2   2.8
 3.    2.8   1.175 1.125 1.225 1.    1.15  1.125 1.175 6.6   1.15  0.975
 7.    1.05  1.    1.175 7.2   1.1   0